### PR TITLE
Fixed broken commands

### PR DESCRIPTION
**Pull request by ulteq**
Might not be the best solution, but it fixes:
> Spawn skyvan press F2 to open the back door. **Press F1. It stops. Press F1 again. It still goes down.** When it goes full down press F1, it goes up.
>
> Master works at it should: **Pressing F2 or F1 instantly opens or closes the door**.

### CODE REVIEW

**Comment by only-a-ptr** [comment]
I like the design, but I'm stumped about the spawning - the `cmb_state` is only set for the contraction `commandbeam_t`, but for the extension `commandbeam_t` it remains null.

Didn't you forget to commit something?

**Comment by ulteq** [comment]
There are two `commandbeam_t` objects. One for the `contract_command` and one for the `extend_command`.
But the command state needs to be shared between the two.
That's why only one `commandbeam_state_t` object exists for both of them.

> Didn't you forget to commit something?

From just looking at the code I'd say it is correct. But I will double check later today.

**Comment by only-a-ptr** [comment]
> That's why only one commandbeam_state_t object exists for both of them.

Sure, what I'm saying is that you forgot to actually share it between the two - you assign it to the contraction object, but not the extension object. 😆

**Comment by ulteq** [comment]
```
contract_command->beams.push_back(cmd_beam);
...
extend_command->beams.push_back(cmd_beam);
```

**Comment by only-a-ptr** [comment]
😳 You're right, I read it wrong the one time and never looked closer

**Pull request merged**
